### ISSUE TITLE
Prototyping specification details

### ISSUE THREAD

**Issue by jj1bdx** [jj1bdx/emprng#1]
@dgud Can you take a look at https://github.com/jj1bdx/emprng/blob/master/emprng.md and see if the specification is OK?

**Comment by dgud** [comment]
Looks good to me

**Comment by jj1bdx** [comment]
@dgud OK thx. I've added the uniform_\* function specs. No change from _random_ module, except for I explicitly stated the return value range as 0.0 < X < 1.0 where X is the value, because this range explanation is required to precisely define the RNG spec.

Reason: in the following calculation quoted from `random.erl` where

``` erlang
1 =< B1 < ?PRIME1,
1 =< B2 < ?PRIME2,
1 =< B3 < ?PRIME3,
```

and

``` erlang
-define(PRIME1, 30269).
-define(PRIME2, 30307).
-define(PRIME3, 30323).
R = B1/?PRIME1 + B2/?PRIME2 + B3/?PRIME3,
R - trunc(R).
```

`R - trunc(R)` will very much unlikely be 0.0, because
- R will never be 0.0, and
- R will very much unlikely to be 1.0 or 2.0 because ?PRIME1, ?PRIME2, ?PRIME3 are not powers of 2 (i.e., the result will be recurring binary numbers) and they are co-prime with each other.

**Comment by jj1bdx** [comment]
I've been running a crude testing code.

```c
#include <stdint.h>
#include <stdio.h>
#include <inttypes.h>

#define PRIME1 (30269)
#define PRIME2 (30307)
#define PRIME3 (30323)
#define MULT ((uint64_t)PRIME1 * (uint64_t)PRIME2 * (uint64_t)PRIME3)

int main(int argc, char *argv[]) {
    uint32_t x, y, z;
    uint64_t s;

    for (x = 1; x < PRIME1; x++) {
        printf("x = %d\n", x);
        for (y = 1; y < PRIME2; y++) {
            for (z = 1; z < PRIME3; z++) {
                s = (((uint64_t)x * (uint64_t)PRIME2 * (uint64_t)PRIME3) +
                     ((uint64_t)y * (uint64_t)PRIME3 * (uint64_t)PRIME1) +
                     ((uint64_t)z * (uint64_t)PRIME1 * (uint64_t)PRIME2));
                if (s % MULT == 0) {
                    printf("x = %d, y = %d, z = %d, s = %" PRIu64 "\n", x, y, z, s);
                }
            }
        }
    }
}
```

**Comment by jj1bdx** [comment]
I've run a crude testing code, in `main/range-check.c`. No result was found when the R could be 0.0.

**Comment by jj1bdx** [comment]
The first version of prototyping the specifications is completed. Closed.
