### ISSUE TITLE
Merging jump functions of exsplus116 and exs1024

### ISSUE THREAD

**Issue by jj1bdx** [jj1bdx/emprng#18]
Jump functions are available for [exsplus116](https://github.com/jj1bdx/exsplus116/) and [exs1024](https://github.com/jj1bdx/exs1024/). The prototypes are completed as `exsplus116:jump/1` and `exs1024:jump/1`.

Points to consider:
- Add a handler for jump function
- For exs64 the jump function is not provided (or even useless); how should the API `rand:jump/1` be implemented?
- Should exs64 jump function be considered?

**Comment by jj1bdx** [comment]
@dgnd Any thought on how `rand:jump/1` be implemented?

My idea is:
* `rand:jump/1` accepts internal state
* If the jump function exists for the algorithm in the given state, the new state with the jump function applied is returned
* If the jump function does not exists for the algorithm, the function returns atom `undefined`

Your idea is appreciated.

**Comment by jj1bdx** [comment]
@dgud  Any thought on how rand:jump/1 be implemented?

My idea is:
- rand:jump/1 accepts internal state
- If the jump function exists for the algorithm in the given state, the new state with the jump function applied is returned
- If the jump function does not exists for the algorithm, the function returns atom undefined

Your idea is appreciated.

**Comment by dgud** [comment]
Isn't it better to return the incoming state if it the jump implementation doesn't exist?
And document it do that, and for which algorithms it exists.

Otherwise the user will wrap the function with 99% of the time.

myjump(State) ->
   case rand:jump(State) of
     error -> %% What to do?
           State;
     NewState -> NewState
end.

But I have not thought it through..:-)

**Comment by jj1bdx** [comment]
@dgud Yes, I want to do exactly like you proposed, regarding the speed. Wrapping with the case statement is absolutely redundant.

My estimation is that in most cases current rand module will be used with exsplus (aka exsplus116) and exs1024 algorithms, and very few people will try to use the jump function for exs64. 

Providing a function such as `rand:is_jump/1` to tell whether the jump algorithm exists for the current state, which returns true when it exists and returns false when it doesn't, will help.

**Comment by dgud** [comment]
I take it back, now that I have thought about it, return error as you do,
it is more safe and lets the user handle that problem, I don't think exs64
is used at all anyway.

**Comment by jj1bdx** [comment]
@dgud So:
- if jump function exists, do the jump and return the jumped state
- if jump function does not exist, return "undefined"

looks OK to you? (Then we don't need to have the is_jump/1 function)

**Comment by dgud** [comment]
{error, not_implemented} in case it does not exist?
Agree that we don't need the is_jump/1 function.

**Comment by jj1bdx** [comment]
`{error, not_implemented}` looks better and agreed (after looked it up at OTP source code and manual).

**Comment by jj1bdx** [comment]
@dgud Can you check out and review this commit? (I've made a new branch `jump-test` for the jump function enhancement) https://github.com/jj1bdx/emprng/commit/7456e7a31a24b4ac30d4518e5499501316d991c4

**Comment by dgud** [comment]
Looks good, though I have not compared to the original code.

**Comment by jj1bdx** [comment]
OTP 19.1 code merged. Jump functions merged to the master/next branch, tagged as 0.5.2. Test suite needed (I've tested the results manually at exsplus116 and exs1024 repositories).

@dgud Is `erlang:error(not_implemented)` usage OK for `exs64_jump/1` dummy function? I thought crashing at this time was appropriate because continuing execution after calling an unimplemented function may cause harm and against the _let it crash_ philosophy.

**Comment by jj1bdx** [comment]
A proposal of test suite for `rand:jump/1`: executing a set of `rand:jump/1` execution results for 100 times, where each set contains 10 times of sequential runs. (100 x 10 = 1000 times in total.) `rand:jump/1` for exsplus takes ~100 times of running time than `rand:next/1`, and for exs1024 it will be ~2000 times.

FYI: `rand:uniform()` is tested at `rand_SUITE:reference/1`, executing 100 sets of `rand:jump/1` execution results, where each set contains 10000 times of sequential runs (100 x 10000 = 1000000 times in total). See `?LOOP` (which is defined as 1000000).

**Comment by jj1bdx** [comment]
@dgud  Jump function test cases added at tag `0.6.0` (latest master). exsplus and exs1024 tested against equivalent C program code.

**Comment by jj1bdx** [comment]
Also refer to:
- https://github.com/jj1bdx/exs1024/commit/924ed550bfa3e64c531e125d9b1a919ccd95f91e
- https://github.com/jj1bdx/exsplus116/commit/40e475adda0ec2a2dbc3c5fe8ac081681169e0c6

**Comment by jj1bdx** [comment]
@dgud Jump function test cases added at tag 0.6.0 (latest master). exsplus and exs1024 tested against equivalent C program code. Also documentation added at `xml-doc/rand.html`.

**Comment by jj1bdx** [comment]
@dgud I have summarized the results and tagged the next release candidate of rand module code (`rand.erl`, `rand_SUITE.erl`, and `rand.xml`) as 0.7.0. I will issue the pull request for merging the code soon (maybe next week). Feel free to comment; you can even review after the PR.

**Comment by jj1bdx** [comment]
@dgud minor doc fix done, tagged as 0.7.1. PR'ed as https://github.com/erlang/otp/pull/1235

**Comment by dgud** [comment]
I've been busy, will take a look at the PR next week.

**Comment by jj1bdx** [comment]
@dgud Thx, no problem.

**Comment by jj1bdx** [comment]
@dgud Added`jump/0`, tagged as 0.8.1, PR in https://github.com/erlang/otp/pull/1235 updated.

**Comment by jj1bdx** [comment]
https://github.com/erlang/otp/pull/1235 merged to the master branch, with spec failures - fixed later as in 0.8.3 (on @jj1bdx's side, to be fixed by OTP Team soon).

**Comment by jj1bdx** [comment]
OTP repository fixed as in https://github.com/erlang/otp/commit/0c84589f2b32018445ab7c1ee995c89e4ec1e836
Version of emprng revised to 0.8.4, test by `make dialyze` worked ok. This completes the merge.
Issue closed.
