### ISSUE TITLE
Code freeze and final version: Version 1.0.0

### ISSUE THREAD

**Issue by jj1bdx** [jj1bdx/emprng#19]
## Version 1.0.0 will be the *last* version of emprng, as included in OTP 20. 

* Code freeze as of 0.9.2: files should be tested in the `next` branch only until Version 1.0.0
* Timing of Version bump to 1.0.0: when the code in OTP are published as OTP 20.
* Further modifications will be directly committed/submitted to OTP.

**Comment by jj1bdx** [comment]
@dgud I didn't know somebody (I thought it was you but looks like I made a mistake, but thanks anyway) made a great improvement in OTP 20.0-rc1 including xoroshiro116+ and deprecation of old algorithms! :)

**Comment by jj1bdx** [comment]
Tag 1.0.0 committed. Issue closed.

**Comment by jj1bdx** [comment]
Removed 1.0.0 tag. I need to credit two more people. After that I will commit 1.0.0 again.

**Comment by jj1bdx** [comment]
@g-andrade and @RaimoNiskanen: thanks for adding a lot of great features and streamlining the code for OTP 20.0-rc1. My apology for not noticing the changes at all.

**Comment by jj1bdx** [comment]
Committed 1.0.0 again. Now closed the issue again.

**Comment by RaimoNiskanen** [comment]
Great!  Thanks!  I did not know you had this repository at all, and it is I who have done most of the  messing around with the code for OTP-20.0; deprecated algorithms and added fixed ones plus xoroshiro116+ (unfortunately a little bit slower than xorshift116+) :-(

**Comment by jj1bdx** [comment]
@RaimoNiskanen

Hi :) I was kind of surprised when I saw xoroshiro116+ in Sebastiano Vigna's site; and even more surprised when things were developed so fast :) Since Erlang VM does not have any rotate-word instructions, it is quite logical that emulating them will make things a bit slower.

I think, nevertheless, the newly added testing code is informative and good, and merging the cryptographic PRNG functions looks good. I guess I need to take a bit of time to review the new code.

**Comment by jj1bdx** [comment]
@RaimoNiskanen I've reviewed the changes and finally understood what you and other contributers have done. You did a great job. I've written a change summary at: http://erlang.org/pipermail/erlang-questions/2017-August/093148.html
